# Generated by Django 2.1.4 on 2018-12-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['user_name', 'review_count', 'average_stars', 'yelper_since'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
